-- Jeu des Points - schema pour comptes, salons et competitions
-- A executer dans Supabase SQL Editor

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    email text not null unique,
    password_hash text not null,
    password_salt text not null,
    pseudo text not null unique,
    role text not null default 'player',
    avatar_url text not null default '',
    country_code text not null default '',
    level integer not null default 1,
    elo integer not null default 1200,
    games_played integer not null default 0,
    wins_total integer not null default 0,
    losses_total integer not null default 0,
    auth_provider text not null default 'password',
    auth_provider_user_id text,
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists public.sessions (
    token_hash text primary key,
    user_id bigint not null references public.users(id) on delete cascade,
    created_at bigint not null,
    expires_at bigint not null,
    last_seen_at bigint not null
);

create table if not exists public.events (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null,
    description text not null default '',
    mode text not null default 'classic',
    status text not null default 'lobby',
    max_players integer not null,
    created_by bigint not null references public.users(id),
    winner_user_id bigint references public.users(id),
    starts_at bigint,
    created_at bigint not null,
    updated_at bigint not null
);

create table if not exists public.event_players (
    event_id bigint not null references public.events(id) on delete cascade,
    user_id bigint not null references public.users(id) on delete cascade,
    display_name text not null,
    is_host boolean not null default false,
    joined_at bigint not null,
    wins integer not null default 0,
    losses integer not null default 0,
    points integer not null default 0,
    primary key (event_id, user_id)
);

create table if not exists public.matches (
    id bigint generated by default as identity primary key,
    event_id bigint not null references public.events(id) on delete cascade,
    round_number integer not null,
    slot_index integer not null,
    player_a_user_id bigint references public.users(id),
    player_b_user_id bigint references public.users(id),
    winner_user_id bigint references public.users(id),
    status text not null default 'pending',
    score_a integer not null default 0,
    score_b integer not null default 0,
    created_at bigint not null,
    updated_at bigint not null
);

create unique index if not exists idx_matches_unique_slot
    on public.matches(event_id, round_number, slot_index);

create index if not exists idx_sessions_expires_at
    on public.sessions(expires_at);

create index if not exists idx_events_status
    on public.events(status);

create index if not exists idx_event_players_event_id
    on public.event_players(event_id);

create index if not exists idx_matches_event_round
    on public.matches(event_id, round_number, slot_index);

create index if not exists idx_users_auth_provider
    on public.users(auth_provider, auth_provider_user_id);

alter table public.users
    add column if not exists avatar_url text not null default '',
    add column if not exists country_code text not null default '',
    add column if not exists level integer not null default 1,
    add column if not exists elo integer not null default 1200,
    add column if not exists games_played integer not null default 0,
    add column if not exists wins_total integer not null default 0,
    add column if not exists losses_total integer not null default 0,
    add column if not exists auth_provider text not null default 'password',
    add column if not exists auth_provider_user_id text;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'users_role_check'
    ) then
        alter table public.users
            add constraint users_role_check check (role in ('player', 'organizer', 'admin'));
    end if;
end
$$;

-- RLS desactivee pour MVP (service role uniquement cote serveur).
alter table public.users disable row level security;
alter table public.sessions disable row level security;
alter table public.events disable row level security;
alter table public.event_players disable row level security;
alter table public.matches disable row level security;
